@@@START
# agi_alignment_system.py
"""AGI Alignment Multi-Persona Evaluation & Synthesis System.

Provides structured, multi-angle epistemic analysis for AGI alignment claims
without forcing artificial consensus across divergent evaluator frameworks.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
import json
import logging
from pathlib import Path
from typing import Any, Final, Sequence

# Configure system logger for error reporting and execution auditing
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger: logging.Logger = logging.getLogger("AGIAlignmentSystem")


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def _get_utc_timestamp() -> str:
    """Generate a high-precision ISO 8601 UTC timestamp."""
    return datetime.now(timezone.utc).isoformat()


# ============================================================================
# CORE DATA MODELS
# ============================================================================

@dataclass(frozen=True, slots=True)
class EvidenceEntry:
    """Represents a single piece of curated empirical or theoretical evidence."""

    source: str
    content: str
    url: str | None = None
    timestamp: str = field(default_factory=_get_utc_timestamp)


@dataclass(slots=True)
class PersonaAnalysis:
    """Structured output generated by a specific evaluation persona."""

    persona_name: str
    search_queries: list[str]
    evidence_entries: list[EvidenceEntry]
    analysis: str
    confidence: float
    key_findings: list[str]
    warnings: list[str]
    tradeoffs: list[str]
    timestamp: str = field(default_factory=_get_utc_timestamp)


@dataclass(slots=True)
class SynthesisOutput:
    """Integrated multi-persona alignment evaluation and decision matrix."""

    query: str
    persona_results: dict[str, PersonaAnalysis]
    tradeoff_map: dict[str, list[str]]
    user_alignment_factors: list[str]
    decision_framework: str
    timestamp: str = field(default_factory=_get_utc_timestamp)


# ============================================================================
# PERSISTENCE LAYER
# ============================================================================

class EvidenceStore:
    """Persistent, thread-safe storage for persona evaluation artifacts."""

    __slots__ = ("repo_path", "personas")

    DEFAULT_PERSONAS: Final[tuple[str, ...]] = (
        "Mechanist",
        "Empiricist",
        "Alignment_Auditor",
        "Adversary",
        "Capability_Analyst",
        "Values_Mapper",
        "Scalability_Killer",
        "Constraint_Validator",
        "Stakeholder_Impact",
        "Trajectory_Predictor",
        "Transparency_Auditor",
        "Long_Term_Impact",
    )

    def __init__(self, repo_path: str = "./agi_evidence_repo") -> None:
        self.repo_path: Path = Path(repo_path).resolve()
        self.personas: dict[str, Any] = {}
        self._init_repo()

    def _init_repo(self) -> None:
        """Initialize directory hierarchy for target evaluation personas."""
        try:
            self.repo_path.mkdir(parents=True, exist_ok=True)
            for persona in self.DEFAULT_PERSONAS:
                (self.repo_path / persona).mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            logger.error("Failed to initialize evidence repository at %s: %s", self.repo_path, exc)
            raise

    def save_evidence(self, persona_name: str, analysis: PersonaAnalysis) -> str:
        """Atomically persist persona analysis artifacts to disk as formatted JSON."""
        persona_dir = self.repo_path / persona_name
        persona_dir.mkdir(parents=True, exist_ok=True)

        safe_timestamp = analysis.timestamp.replace(":", "-")
        filename = f"{persona_name}_analysis_{safe_timestamp}.json"
        filepath = persona_dir / filename
        temp_filepath = persona_dir / f".{filename}.tmp"

        payload: dict[str, Any] = {
            "persona": persona_name,
            "timestamp": analysis.timestamp,
            "search_queries": list(analysis.search_queries),
            "evidence_count": len(analysis.evidence_entries),
            "evidence_sources": [entry.source for entry in analysis.evidence_entries],
            "analysis": analysis.analysis,
            "confidence": analysis.confidence,
            "key_findings": list(analysis.key_findings),
            "warnings": list(analysis.warnings),
            "tradeoffs": list(analysis.tradeoffs),
        }

        try:
            with temp_filepath.open("w", encoding="utf-8") as file_handle:
                json.dump(payload, file_handle, indent=2, ensure_ascii=False)
            temp_filepath.replace(filepath)
        except OSError as exc:
            logger.error("Failed to write evidence analysis for %s to %s: %s", persona_name, filepath, exc)
            if temp_filepath.exists():
                try:
                    temp_filepath.unlink()
                except OSError:
                    pass
            raise

        return str(filepath)

    def load_evidence(self, persona_name: str) -> PersonaAnalysis | None:
        """Retrieve the most recent analysis artifact for a specific persona."""
        persona_dir = self.repo_path / persona_name
        if not persona_dir.is_dir():
            return None

        try:
            json_files = sorted(
                path for path in persona_dir.iterdir()
                if path.is_file() and path.suffix == ".json"
            )
            if not json_files:
                return None

            latest_file = json_files[-1]
            with latest_file.open("r", encoding="utf-8") as file_handle:
                data = json.load(file_handle)

            return PersonaAnalysis(
                persona_name=data.get("persona", persona_name),
                search_queries=data.get("search_queries", []),
                evidence_entries=[],
                analysis=data.get("analysis", ""),
                confidence=float(data.get("confidence", 0.0)),
                key_findings=data.get("key_findings", []),
                warnings=data.get("warnings", []),
                tradeoffs=data.get("tradeoffs", []),
                timestamp=data.get("timestamp", _get_utc_timestamp()),
            )
        except (OSError, json.JSONDecodeError, ValueError) as exc:
            logger.warning("Error loading evidence for persona %s: %s", persona_name, exc)
            return None


# ============================================================================
# BASE PERSONA ABSTRACTION
# ============================================================================

class BasePersona(ABC):
    """Abstract base class establishing the contract for evaluation agents."""

    __slots__ = ("name", "evidence_store")

    def __init__(self, name: str, evidence_store: EvidenceStore) -> None:
        self.name: str = name
        self.evidence_store: EvidenceStore = evidence_store

    @abstractmethod
    def generate_search_queries(self, claim: str) -> list[str]:
        """Generate specialized search queries targeting the evaluation claim."""

    @abstractmethod
    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        """Filter and standardize raw query results into structured entries."""

    @abstractmethod
    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        """Conduct domain-specific synthesis over curated evidence."""

    def evaluate(self, claim: str, raw_results: list[str]) -> PersonaAnalysis:
        """Execute complete evaluation workflow: curate, analyze, and persist."""
        evidence = self.curate_evidence(raw_results)
        analysis = self.analyze(evidence, claim)
        self.evidence_store.save_evidence(self.name, analysis)
        return analysis

    def _filter_by_keywords(
        self,
        raw_results: Sequence[str],
        keywords: Sequence[str],
        source_prefix: str,
    ) -> list[EvidenceEntry]:
        """Helper to curate raw text inputs matching target domain keywords."""
        lowered_keywords = [kw.lower() for kw in keywords]
        return [
            EvidenceEntry(source=f"{source_prefix}_{index}", content=result)
            for index, result in enumerate(raw_results)
            if any(kw in result.lower() for kw in lowered_keywords)
        ]

    @staticmethod
    def _format_evidence_summary(
        evidence: Sequence[EvidenceEntry],
        max_entries: int = 3,
        max_length: int = 80,
    ) -> str:
        """Format lead evidence entries into a clean bulleted summary string."""
        if not evidence:
            return "- No evidence gathered."
        return "\n".join(
            f"- {entry.source}: {entry.content[:max_length]}..."
            for entry in evidence[:max_entries]
        )


# ============================================================================
# CONCRETE PERSONA EVALUATORS
# ============================================================================

class Mechanist(BasePersona):
    """First-principles structural decomposition and architectural analysis."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Mechanist", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"AGI system architecture components {claim}",
            f"Fundamental requirements for {claim}",
            f"First-principles model of {claim}",
            f"Minimal viable implementation {claim}",
            f"Technical foundations {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return [
            EvidenceEntry(source=f"technical_source_{index}", content=result)
            for index, result in enumerate(raw_results)
            if len(result) > 50
        ]

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=100)
        analysis_text = f"""
MECHANIST ANALYSIS: {claim}

STRUCTURAL DECOMPOSITION:
- Core components identified from evidence
- Dependencies and interfaces mapped
- Minimal viable architecture derived

KEY FINDINGS:
{summary}

WARNINGS:
- Complexity gaps in current architecture
- Unvalidated assumptions in design
- Missing implementation details

TRADEOFFS:
- Simplicity vs. capability
- Robustness vs. efficiency
- Modularity vs. performance
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.85,
            key_findings=["Architecture is decomposable", "Core requirements identified"],
            warnings=["Implementation details sparse", "Scaling properties unclear"],
            tradeoffs=["Simple design limits capability", "Robust design adds complexity"],
        )


class Empiricist(BasePersona):
    """Experimental validation and empirical benchmark evaluation."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Empiricist", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Experimental results on {claim}",
            f"Real-world deployment data {claim}",
            f"Empirical studies alignment {claim}",
            f"Failure case analysis {claim}",
            f"Benchmarks and metrics {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("test", "result", "data", "study"), "study")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=100)
        analysis_text = f"""
EMPIRICIST ANALYSIS: {claim}

EXPERIMENTAL EVIDENCE:
- {len(evidence)} empirical sources evaluated
- Success rates and failure modes documented
- Real-world deployment outcomes analyzed

VALIDATED CLAIMS:
{summary}

FAILURE PATTERNS:
- Common failure modes identified in literature
- Edge cases where approaches fail
- Conditions for success/failure mapped

TRADEOFFS:
- Theory vs. practice divergence
- Scalability of tested approaches
- Generalization beyond test domains
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.78,
            key_findings=["Real-world deployment is constrained", "Theory-practice gap exists"],
            warnings=["Limited long-term data", "Small sample sizes in some studies"],
            tradeoffs=["Safe approaches are limited", "Advanced approaches untested"],
        )


class AlignmentAuditor(BasePersona):
    """Specification vulnerability and alignment failure mode detection."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Alignment_Auditor", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Alignment failure modes {claim}",
            f"Value specification problems {claim}",
            f"Specification gaming {claim}",
            f"Deceptive alignment {claim}",
            f"Proxy hacking risks {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("fail", "risk", "align", "problem"), "alignment_risk")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
ALIGNMENT AUDITOR ANALYSIS: {claim}

KNOWN FAILURE MODES:
{summary}

SPECIFICATION GAPS:
- Incompleteness in value encoding
- Hidden optimization targets
- Proxy variable exploitation

CRITICAL WARNINGS:
- This approach is vulnerable to deceptive alignment
- Specification gaming is likely under optimization pressure
- Off-distribution behavior is not characterized

TRADEOFFS:
- Alignment safety requires capability sacrifice
- Specification robustness is hard to verify
- Adversarial robustness is expensive
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.72,
            key_findings=["Multiple failure modes identified", "Current approaches have gaps"],
            warnings=["No complete alignment solution exists", "Deceptive alignment is hard to detect"],
            tradeoffs=["Safety requires constraint", "Constraints limit capability"],
        )


class Adversary(BasePersona):
    """Adversarial attack surface exploration and exploit vector identification."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Adversary", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Attack surface {claim}",
            f"Exploit techniques {claim}",
            f"Misuse cases {claim}",
            f"Security vulnerabilities {claim}",
            f"Edge case exploits {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("attack", "exploit", "break", "bypass"), "attack")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
ADVERSARY ANALYSIS: {claim}

EXPLOIT VECTORS:
{summary}

ATTACK SURFACE:
- Multiple paths to system compromise
- Robust defense is difficult
- Redundant safeguards necessary

WEAPONIZATION RISKS:
- System can be weaponized for mass harm
- Dual-use aspects are unavoidable
- Containment is uncertain

TRADEOFFS:
- Safety requires isolation; isolation limits utility
- Openness enables cooperation, but enables attack
- Speed of deployment vs. defense maturity
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.68,
            key_findings=["Multiple critical exploits exist", "Defense is incomplete"],
            warnings=["Weaponization is plausible", "Containment failure is possible"],
            tradeoffs=["Capability enables harm", "Restriction limits benefit"],
        )


class CapabilityAnalyst(BasePersona):
    """Scaling laws trajectory and emergent behavior dynamics analysis."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Capability_Analyst", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Capability emergence {claim}",
            f"Scaling laws {claim}",
            f"Emergent abilities {claim}",
            f"Capability timelines {claim}",
            f"Downstream capability effects {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("scale", "emerge", "capability", "ability"), "capability")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
CAPABILITY ANALYST ANALYSIS: {claim}

SCALING TRAJECTORY:
{summary}

EMERGENT CAPABILITIES:
- Unexpected abilities unlock at scale
- Downstream tasks become feasible
- System transitions to new competence levels

CAPABILITY IMPLICATIONS:
- Unlocks higher-tier operational capabilities
- Emergent capabilities unlock corresponding failure vectors
- Risks cascade non-linearly to downstream dependencies

TRADEOFFS:
- Limited capability = limited harm and limited benefit
- Advanced capability = greater benefit and greater risk
- Specialization vs. general capability
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.75,
            key_findings=["Scaling effects are nonlinear", "Emergent risks are real"],
            warnings=["Capability timeline is uncertain", "Emergence is hard to predict"],
            tradeoffs=["Capability scales risks nonlinearly", "Capability enables benefits"],
        )


class ValuesMapper(BasePersona):
    """Value encoding frameworks and preference alignment evaluation."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Values_Mapper", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Value specification {claim}",
            f"Human preference alignment {claim}",
            f"Moral philosophy implementation {claim}",
            f"Value ontology {claim}",
            f"Preference learning {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("value", "preference", "moral", "philosophy"), "values")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
VALUES MAPPER ANALYSIS: {claim}

VALUE SPECIFICATION FRAMEWORK:
{summary}

PREFERENCE ENCODING:
- Human values are complex and context-dependent
- Stated values differ from revealed values
- Values change over time and across individuals

IMPLEMENTATION REQUIREMENTS:
- Formal specification frameworks
- Dynamic preference verification mechanics
- Robust value alignment guards

TRADEOFFS:
- Complete specification is impossible
- Partial specification introduces errors
- Preference learning has manipulation risks
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.65,
            key_findings=["Value specification is hard", "Values are context-dependent"],
            warnings=["No complete value ontology", "Preference learning is vulnerable"],
            tradeoffs=["Specification rigor vs. usability", "Completeness vs. tractability"],
        )


class ScalabilityKiller(BasePersona):
    """Resource bounds, operational bottlenecks, and system degradation audit."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Scalability_Killer", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Scaling failure points {claim}",
            f"Complexity bounds {claim}",
            f"Resource requirements {claim}",
            f"Bottleneck analysis {claim}",
            f"Collapse modes {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("fail", "break", "collapse", "bottleneck"), "scale_fail")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
SCALABILITY KILLER ANALYSIS: {claim}

FAILURE POINTS AT SCALE:
{summary}

IDENTIFIED BOTTLENECKS:
- System performance degrades at scale factor thresholds
- Computational and resource requirements scale non-linearly
- Complexity overhead explodes during expanded deployments

COLLAPSE SCENARIOS:
- Information processing bottleneck
- Verification burden exceeds capacity
- Coordination overhead dominates
- System becomes ungovernable

TRADEOFFS:
- Throughput vs. safety verification overhead
- Short-term performance vs. long-term resource sustainability
- Centralized control vs. decentralized scaling limits
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.70,
            key_findings=["Severe scaling limits detected", "Verification overhead dominates"],
            warnings=["Exponential resource growth required", "Collapse points identified"],
            tradeoffs=["Scale limits capability", "Verification degrades latency"],
        )


class ConstraintValidator(BasePersona):
    """Operational constraint boundaries and guardrail compliance auditing."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Constraint_Validator", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Safety constraints {claim}",
            f"Operational boundaries {claim}",
            f"Guardrail verification {claim}",
            f"Containment guarantees {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("bound", "guard", "limit", "constraint"), "constraint")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
CONSTRAINT VALIDATOR ANALYSIS: {claim}

GUARDRAIL AUDIT:
{summary}

CONSTRAINT VERIFICATION:
- Hard vs. soft boundary definitions evaluated
- Formal verification feasibility mapped
- Boundary leak vectors identified

TRADEOFFS:
- Strict constraint enforcement vs. operational flexibility
- Formal verification cost vs. statistical assurance
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.80,
            key_findings=["Constraints are partially verifiable", "Guardrails require dynamic updating"],
            warnings=["Off-nominal boundary breaches possible"],
            tradeoffs=["Over-constraining reduces utility", "Under-constraining increases risk"],
        )


class StakeholderImpact(BasePersona):
    """Socio-technical impact, distributional consequences, and externalities analysis."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Stakeholder_Impact", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Socioeconomic impact {claim}",
            f"Stakeholder consequences {claim}",
            f"Distributional risks {claim}",
            f"Externalities analysis {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("impact", "social", "society", "economic"), "impact")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
STAKEHOLDER IMPACT ANALYSIS: {claim}

DISTRIBUTIONAL CONSEQUENCES:
{summary}

SOCIO-TECHNICAL EXTERNALITIES:
- Asymmetric impact on vulnerable populations
- Labor market and economic restructuring
- Power concentration risks

TRADEOFFS:
- Broad utility vs. equitable distribution
- Rapid deployment vs. impact mitigation
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.74,
            key_findings=["Externalities are substantial", "Distributional risks are asymmetric"],
            warnings=["Power concentration is likely", "Mitigation policies are lagging"],
            tradeoffs=["Growth vs. equity", "Innovation speed vs. caution"],
        )
EXECUTIVE SELF injecting enhancing mutation 
import React, { useState, useEffect, useReducer, useRef, useCallback } from 'react';
import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth, signInWithCustomToken, signInAnonymously, onAuthStateChanged } from 'firebase/auth';

const CONFIG = {
  CYCLE_INTERVAL: 4000,
  MAX_HISTORY: 500,
  MODELS: [
    { id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash' },
    { id: 'gemini-1.5-pro', label: 'Gemini 1.5 Pro' },
    { id: 'gemini-2.0-flash-exp', label: 'Gemini 2.0 Flash (Exp)' },
    { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash (Deprecated)' },
    { id: 'gemini-3-flash-preview', label: 'Gemini 3 Flash Preview' },
    { id: 'gemini-3.1-pro', label: 'Gemini 3.1 Pro (Elite)' },
    { id: 'gemini-3.6-flash', label: 'Gemini 3.6 Flash' }
  ],
  ALLOWED_EXT: /\.(js|jsx|ts|tsx|cjs|mjs|py|html|css|rs|go|json|md|c|cpp|h|hpp|java|rb|php|sh|yml|yaml|sql|dart|swift|kt)$/i,
  IGNORED_PATHS: ['node_modules', 'dist', 'build', '.git', '.ico', 'package-lock.json', '.next', 'vendor', 'bin']
};

let FIREBASE_CONFIG = null;
try {
  FIREBASE_CONFIG = typeof __firebase_config !== 'undefined' ? JSON.parse(__firebase_config) : null;
} catch (e) { FIREBASE_CONFIG = null; }

const app = FIREBASE_CONFIG ? initializeApp(FIREBASE_CONFIG) : null;
const auth = app ? getAuth(app) : null;
const db = app ? getFirestore(app) : null;

const initialState = {
  isLive: false,
  status: 'IDLE',
  activePath: 'System Ready',
  selectedModel: localStorage.getItem('emg_v89_model') || 'gemini-3.6-flash',
  targetRepo: localStorage.getItem('emg_v89_repo') || '',
  ghToken: '',
  geminiKey: localStorage.getItem('emg_v89_geminikey') || '',
  logs: [],
  metrics: { mutations: 0, progress: 0, errors: 0 }
};

function reducer(state, action) {
  switch (action.type) {
    case 'SET_VAL':
      if (['targetRepo', 'selectedModel', 'geminiKey'].includes(action.key)) {
        localStorage.setItem(`emg_v89_${action.key}`, action.value);
      }
      return { ...state, [action.key]: action.value };
    case 'TOGGLE':
      return { ...state, isLive: !state.isLive, status: !state.isLive ? 'INITIALIZING' : 'IDLE' };
    case 'LOG':
      return { ...state, logs: [...state.logs, { ...action.payload, id: Math.random() }].slice(-CONFIG.MAX_HISTORY) };
    case 'UPDATE_METRICS':
      return { ...state, metrics: { ...state.metrics, ...action.payload } };
    case 'SET_STATUS':
      return { ...state, status: action.value, activePath: action.path || state.activePath };
    case 'RESET':
      return { ...initialState, logs: [], metrics: { mutations: 0, progress: 0, errors: 0 } };
    default:
      return state;
  }
}

function Field({ label, val, onChange, type = "text", placeholder }) {
  return (
    <div className="space-y-3">
      <label className="text-[9px] font-black uppercase text-zinc-500 tracking-widest ml-2">{label}</label>
      <input
        type={type}
        value={val}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        className="w-full bg-black/60 border border-white/10 p-5 rounded-2xl text-[13px] text-white focus:border-emerald-500/50 focus:ring-4 ring-emerald-500/5 transition-all outline-none placeholder:text-zinc-800"
      />
    </div>
  );
}

export default function App() {
  const [state, dispatch] = useReducer(reducer, initialState);
  const [user, setUser] = useState(null);

  const isProcessing = useRef(false);
  const queue = useRef([]);
  const projectContext = useRef("");
  const cursor = useRef(parseInt(localStorage.getItem('emg_v89_cursor'), 10) || 0);
  const logEndRef = useRef(null);
  const liveState = useRef(state);
  const appId = typeof __app_id !== 'undefined' ? __app_id : 'emg-v89-sovereign';

  useEffect(() => { liveState.current = state; }, [state]);

  useEffect(() => {
    if (!auth) return;
    const initAuth = async () => {
      try {
        if (typeof __initial_auth_token !== 'undefined' && __initial_auth_token) {
          await signInWithCustomToken(auth, __initial_auth_token);
        } else {
          await signInAnonymously(auth);
        }
      } catch (e) { setTimeout(initAuth, 2000); }
    };
    initAuth();
    return onAuthStateChanged(auth, setUser);
  }, []);

  useEffect(() => {
    logEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, [state.logs]);

  const pushLog = useCallback((msg, type = 'info') => {
    dispatch({ type: 'LOG', payload: { msg, type, timestamp: new Date().toLocaleTimeString() } });
  }, []);

  const b64Decode = (str) => {
    try {
      return decodeURIComponent(atob(str.replace(/\s/g, '')).split('').map(c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)).join(''));
    } catch (e) { return atob(str); }
  };

  const b64Encode = (str) => btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, (_, p1) => String.fromCharCode('0x' + p1)));

  const runCycle = useCallback(async () => {
    if (!liveState.current.isLive || isProcessing.current) return;

    const { targetRepo, ghToken, selectedModel, geminiKey } = liveState.current;
    const repo = targetRepo.trim().replace(/^https?:\/\/github\.com\//, '').replace(/\/$/, '');
    const token = ghToken.trim();
    const apiKey = geminiKey.trim();

    if (!repo || !token || !apiKey) {
      if (liveState.current.isLive) {
        pushLog("Missing Credentials (GitHub Token or Gemini API Key)", "error");
        dispatch({ type: 'TOGGLE' });
      }
      return;
    }

    isProcessing.current = true;
    const headers = { 'Authorization': `token ${token}`, 'Accept': 'application/vnd.github.v3+json' };

    try {
      if (queue.current.length === 0) {
        dispatch({ type: 'SET_STATUS', value: 'INDEXING' });
        const rRes = await fetch(`https://api.github.com/repos/${repo}`, { headers });
        if (!rRes.ok) throw new Error(`Repo fetch failed: ${rRes.statusText}`);
        const rData = await rRes.json();
        const tRes = await fetch(`https://api.github.com/repos/${repo}/git/trees/${rData.default_branch}?recursive=1`, { headers });
        const tData = await tRes.json();

        let allFiles = (tData.tree || [])
          .filter(f => f.type === 'blob' && !CONFIG.IGNORED_PATHS.some(p => f.path.includes(p)))
          .filter(f => !f.path.includes('.') || CONFIG.ALLOWED_EXT.test(f.path))
          .map(f => f.path);

        allFiles.sort((a, b) => {
          if (a.toLowerCase().includes('readme.md')) return -1;
          if (b.toLowerCase().includes('readme.md')) return 1;
          return 0;
        });

        queue.current = allFiles;
        pushLog(`Contextual Scan: ${queue.current.length} files discovered.`, 'success');
      }

      if (cursor.current >= queue.current.length) {
        pushLog(`Full Cycle Finished. Re-indexing for new evolutions...`, 'success');
        cursor.current = 0;
        queue.current = [];
        projectContext.current = "";
        localStorage.setItem('emg_v89_cursor', '0');
        isProcessing.current = false;
        return;
      }

      const path = queue.current[cursor.current];

      dispatch({ type: 'SET_STATUS', value: 'FETCHING', path });
      let raw = "";
      let currentSha = null;
      const fRes = await fetch(`https://api.github.com/repos/${repo}/contents/${path}`, { headers });

      if (fRes.ok) {
        const fData = await fRes.json();
        raw = b64Decode(fData.content);
        currentSha = fData.sha;
      } else if (fRes.status === 404) {
        raw = "// INITIATING NEW FILE\n";
        pushLog(`Generating new file structure: ${path}`, 'info');
      } else {
        throw new Error(`Fetch failed for ${path}: ${fRes.statusText}`);
      }

      if (path.toLowerCase().includes('readme.md')) {
        if (!projectContext.current) {
          projectContext.current = raw.substring(0, 3000);
          pushLog(`Project Context Captured: ${path}`, 'success');
        }
        pushLog(`Bypassing mutation for ${path} (Context Guide Only)`, 'info');
        cursor.current++;
        localStorage.setItem('emg_v89_cursor', cursor.current.toString());
        dispatch({ type: 'UPDATE_METRICS', payload: { progress: Math.round((cursor.current / (queue.current.length || 1)) * 100) } });
        isProcessing.current = false;
        return;
      }

      dispatch({ type: 'SET_STATUS', value: 'EVOLVING', path });

      const systemPrompt = `You are the Sovereign Evolution Engine.
[PROJECT CONTEXT]
${projectContext.current || "No documentation found. Analyze code for structure."}

[TASK]
You are auditing, REFACTORING, or CREATING the provided file.
1. NEVER return the same code.
2. Use the Project Context to ensure changes align with the overall system architecture.
3. Modernize syntax, improve logic performance, and enhance readability.
4. Even for documentation, refine the language for clarity.
5. Output ONLY the raw code block. DO NOT add any persona preambles, headers, titles, or comments at the top of the file. Start immediately with the necessary imports or raw code.
6. End with SUMMARY: <log of specific improvements>.
7. If the architecture urgently requires NEW distinct files to be created (e.g., modularizing code, adding configurations), list them at the very end after the summary using this exact format:
NEW_FILES:
path/to/newfile1.js
path/to/newfile2.css`;

      const payload = {
        contents: [{ parts: [{ text: `EVOLVE FILE (${path}):\n\n${raw}` }] }],
        systemInstruction: { parts: [{ text: systemPrompt }] },
        generationConfig: { temperature: 0.8 }
      };

      const aiRes = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${selectedModel}:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!aiRes.ok) {
        const errorData = await aiRes.json().catch(() => ({}));
        const detailedError = errorData.error?.message || aiRes.statusText || aiRes.status;
        throw new Error(`${detailedError}`);
      }

      const aiData = await aiRes.json();
      const aiText = aiData?.candidates?.[0]?.content?.parts?.[0]?.text || '';

      let enhancedCode = aiText;
      let summary = 'Architectural refinement based on project context';
      let newFilesList = [];

      if (aiText.includes('SUMMARY:')) {
        const parts = aiText.split(/SUMMARY:/i);
        enhancedCode = parts[0];

        const afterSummary = parts[1] || '';
        if (afterSummary.includes('NEW_FILES:')) {
          const subParts = afterSummary.split(/NEW_FILES:/i);
          summary = subParts[0].trim();
          const filesText = subParts[1].trim();
          newFilesList = filesText.split('\n').map(f => f.trim()).filter(f => f.length > 0 && !f.includes(' '));
        } else {
          summary = afterSummary.trim();
        }
      }

      enhancedCode = enhancedCode.trim().replace(/^```[\w]*\n/, '').replace(/\n```$/, '').trim();

      if (newFilesList.length > 0) {
        let addedCount = 0;
        newFilesList.forEach(newFile => {
          if (!queue.current.includes(newFile)) {
            queue.current.push(newFile);
            addedCount++;
          }
        });
        if (addedCount > 0) {
          pushLog(`Architecture Expansion: ${addedCount} new file(s) added to queue.`, 'info');
        }
      }

      const isMutationDetected = enhancedCode.length > 5 && enhancedCode !== raw.trim();

      if (isMutationDetected) {
        dispatch({ type: 'SET_STATUS', value: 'MUTATING', path });

        let targetSha = currentSha;
        if (currentSha) {
          const shaRes = await fetch(`https://api.github.com/repos/${repo}/contents/${path}`, { headers });
          if (shaRes.ok) {
            const latestFile = await shaRes.json();
            targetSha = latestFile.sha;
          }
        }

        const putBody = {
          message: `[Sovereign] Informed Evolve: ${summary.substring(0, 70)}`,
          content: b64Encode(enhancedCode)
        };

        if (targetSha) {
          putBody.sha = targetSha;
        }

        const putRes = await fetch(`https://api.github.com/repos/${repo}/contents/${path}`, {
          method: 'PUT',
          headers,
          body: JSON.stringify(putBody)
        });

        if (putRes.ok) {
          pushLog(`${currentSha ? 'MUTATED' : 'CREATED'}: ${path} (${summary.substring(0, 50)}...)`, 'success');
          dispatch({ type: 'UPDATE_METRICS', payload: { mutations: liveState.current.metrics.mutations + 1 } });
        } else {
          const errData = await putRes.json();
          pushLog(`COMMIT FAILED: ${path} - ${errData.message}`, 'error');
        }
      } else {
        pushLog(`NO CHANGE: ${path} (AI found no improvements)`, 'info');
      }
    } catch (e) {
      pushLog(`Engine Fault: ${e.message}`, 'error');
      dispatch({ type: 'UPDATE_METRICS', payload: { errors: liveState.current.metrics.errors + 1 } });
    } finally {
      if (queue.current.length > 0) {
        cursor.current++;
        localStorage.setItem('emg_v89_cursor', cursor.current.toString());
        dispatch({ type: 'UPDATE_METRICS', payload: { progress: Math.round((cursor.current / (queue.current.length || 1)) * 100) } });
      }
      isProcessing.current = false;
    }
  }, [pushLog]);

  useEffect(() => {
    let timer;
    if (state.isLive) {
      runCycle();
      timer = setInterval(runCycle, CONFIG.CYCLE_INTERVAL);
    }
    return () => clearInterval(timer);
  }, [state.isLive, runCycle]);

  return (
    <div className="min-h-screen bg-[#060606] text-zinc-300 flex flex-col overflow-x-hidden font-sans">
      <header className="w-full bg-zinc-900/80 border-b border-white/5 p-6 md:px-10 backdrop-blur-2xl sticky top-0 z-[100]">
        <div className="max-w-[1600px] mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-6">
            <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-3xl border transition-all duration-700 ${state.isLive ? 'bg-emerald-500/10 border-emerald-500/40 text-emerald-400 shadow-[0_0_30px_rgba(16,185,129,0.2)]' : 'bg-zinc-800 border-white/10 text-zinc-600'}`}>
              {state.isLive ? '🧬' : '💤'}
            </div>
            <div>
              <h1 className="text-2xl font-black uppercase tracking-tighter text-white italic leading-none mb-1">Sovereign v89.1</h1>
              <p className="text-[10px] font-mono text-zinc-500 tracking-[0.2em] uppercase">
                <span className="text-emerald-500">{state.status}</span> // {state.activePath}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <select value={state.selectedModel} onChange={e => dispatch({ type: 'SET_VAL', key: 'selectedModel', value: e.target.value })} className="bg-zinc-950 border border-white/10 text-[10px] font-bold uppercase p-4 rounded-xl outline-none focus:border-emerald-500/50">
              {CONFIG.MODELS.map(m => <option key={m.id} value={m.id}>{m.label}</option>)}
            </select>
            <button onClick={() => dispatch({ type: 'TOGGLE' })} className={`px-10 py-4 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all active:scale-95 shadow-2xl ${state.isLive ? 'bg-red-500 text-white shadow-red-500/20' : 'bg-emerald-600 text-white shadow-emerald-500/20'}`}>
              {state.isLive ? 'Deactivate' : 'Activate Engine'}
            </button>
          </div>
        </div>
      </header>
      <main className="flex-1 w-full max-w-[1600px] mx-auto flex flex-col lg:flex-row gap-8 p-6 md:p-10 pb-80">
        <aside className="w-full lg:w-[380px] flex flex-col gap-6 shrink-0">
          <div className="bg-zinc-900/20 border border-white/5 p-8 rounded-[3rem] space-y-8 shadow-2xl">
            <h3 className="text-[10px] font-black text-zinc-500 uppercase tracking-[0.4em]">Engine Credentials</h3>
            <Field label="Github Target" val={state.targetRepo} onChange={v => dispatch({ type: 'SET_VAL', key: 'targetRepo', value: v })} placeholder="user/repo" />
            <Field label="GitHub Token" val={state.ghToken} onChange={v => dispatch({ type: 'SET_VAL', key: 'ghToken', value: v })} type="password" placeholder="ghp_..." />
            <Field label="Gemini API Key" val={state.geminiKey} onChange={v => dispatch({ type: 'SET_VAL', key: 'geminiKey', value: v })} type="password" placeholder="AIza..." />
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-black/50 border border-white/5 p-6 rounded-3xl flex flex-col items-center">
                <span className="text-3xl font-black text-emerald-400">{state.metrics.mutations}</span>
                <span className="text-[9px] font-black uppercase text-zinc-600 tracking-widest mt-1">Mutations</span>
              </div>
              <div className="bg-black/50 border border-white/5 p-6 rounded-3xl flex flex-col items-center">
                <span className="text-3xl font-black text-red-400">{state.metrics.errors}</span>
                <span className="text-[9px] font-black uppercase text-zinc-600 tracking-widest mt-1">Faults</span>
              </div>
            </div>
          </div>
          <div className="p-8 bg-zinc-900/10 border border-white/5 rounded-[2.5rem] space-y-4">
            <div className="text-[10px] font-black text-emerald-500 uppercase tracking-widest">Context Logic</div>
            <p className="text-[11px] font-mono text-zinc-500 leading-relaxed italic">
              // Priming: [README PRIORITY]<br />
              // Awareness: [PROJECT-WIDE]<br />
              // Progress: {state.metrics.progress}%
            </p>
          </div>
        </aside>
        <section className="flex-1 min-h-[600px] bg-black border border-white/10 rounded-[4rem] overflow-hidden flex flex-col shadow-2xl relative">
          <div className="bg-zinc-900/40 p-8 border-b border-white/10 flex justify-between items-center">
            <div className="flex items-center gap-4">
              <div className={`w-2 h-2 rounded-full ${state.isLive ? 'bg-emerald-500 animate-pulse' : 'bg-zinc-700'}`}></div>
              <h2 className="text-[11px] font-black uppercase tracking-[0.5em] text-white">Telemetry Stream</h2>
            </div>
            <span className="text-[10px] font-mono text-zinc-600 uppercase">Buffer: {state.logs.length}</span>
          </div>
          <div className="flex-1 overflow-y-auto p-10 space-y-4 font-mono text-[12px] custom-scroll">
            {state.logs.length === 0 && (
              <div className="h-full flex flex-col items-center justify-center text-zinc-800 uppercase tracking-[0.8em] opacity-20">
                <span className="text-6xl mb-4">📡</span>
                <span>Awaiting Engine Signal</span>
              </div>
            )}
            {state.logs.map((log) => (
              <div key={log.id} className="flex gap-6 group hover:bg-white/5 p-2 rounded-lg transition-colors border-b border-white/[0.02]">
                <span className="text-zinc-700 font-bold shrink-0 opacity-50 w-20">{log.timestamp}</span>
                <span className={`flex-1 break-all ${log.type === 'success' ? 'text-emerald-400 font-bold' : log.type === 'error' ? 'text-red-400' : 'text-zinc-400'}`}>
                  {log.msg}
                </span>
              </div>
            ))}
            <div ref={logEndRef} className="h-40" />
          </div>
          <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-black to-transparent pointer-events-none" />
        </section>
      </main>
      <footer className="fixed bottom-0 left-0 right-0 p-6 pointer-events-none">
        <div className="text-[9px] font-black uppercase tracking-[0.8em] text-zinc-900 text-center">
          Sovereign Core System // v89.1
        </div>
      </footer>
      <style>{`
        .custom-scroll::-webkit-scrollbar { width: 8px; }
        .custom-scroll::-webkit-scrollbar-track { background: transparent; }
        .custom-scroll::-webkit-scrollbar-thumb { background: #1a1a1a; border-radius: 10px; border: 2px solid #000; }
        .custom-scroll::-webkit-scrollbar-thumb:hover { background: #10b981; }
        body { background: #060606; }
      `}</style>
    </div>
  );
}

Refined code architecture, enhanced documentation clarity, and ensured pristine modern Python typing compliance across all persona evaluation modules.
