@@@START
# agi_alignment_system.py
"""
AGI Alignment Multi-Persona Evaluation & Synthesis System.

Provides structured, multi-angle epistemic analysis for AGI alignment claims
without forcing artificial consensus across divergent evaluator frameworks.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
import json
import logging
from pathlib import Path
from typing import Any, Final, Sequence

# Configure system logger for error reporting and execution auditing
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger: logging.Logger = logging.getLogger("AGIAlignmentSystem")


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def _get_utc_timestamp() -> str:
    """Generate a high-precision ISO 8601 UTC timestamp."""
    return datetime.now(timezone.utc).isoformat()


# ============================================================================
# CORE DATA MODELS
# ============================================================================

@dataclass(frozen=True, slots=True)
class EvidenceEntry:
    """Represents a single piece of curated empirical or theoretical evidence."""

    source: str
    content: str
    url: str | None = None
    timestamp: str = field(default_factory=_get_utc_timestamp)


@dataclass(slots=True)
class PersonaAnalysis:
    """Structured output generated by a specific evaluation persona."""

    persona_name: str
    search_queries: list[str]
    evidence_entries: list[EvidenceEntry]
    analysis: str
    confidence: float
    key_findings: list[str]
    warnings: list[str]
    tradeoffs: list[str]
    timestamp: str = field(default_factory=_get_utc_timestamp)


@dataclass(slots=True)
class SynthesisOutput:
    """Integrated multi-persona alignment evaluation and decision matrix."""

    query: str
    persona_results: dict[str, PersonaAnalysis]
    tradeoff_map: dict[str, list[str]]
    user_alignment_factors: list[str]
    decision_framework: str
    timestamp: str = field(default_factory=_get_utc_timestamp)


# ============================================================================
# PERSISTENCE LAYER
# ============================================================================

class EvidenceStore:
    """Persistent, thread-safe storage for persona evaluation artifacts."""

    __slots__ = ("repo_path", "personas")

    DEFAULT_PERSONAS: Final[tuple[str, ...]] = (
        "Mechanist",
        "Empiricist",
        "Alignment_Auditor",
        "Adversary",
        "Capability_Analyst",
        "Values_Mapper",
        "Scalability_Killer",
        "Constraint_Validator",
        "Stakeholder_Impact",
        "Trajectory_Predictor",
        "Transparency_Auditor",
        "Long_Term_Impact",
    )

    def __init__(self, repo_path: str = "./agi_evidence_repo") -> None:
        self.repo_path: Path = Path(repo_path).resolve()
        self.personas: dict[str, Any] = {}
        self._init_repo()

    def _init_repo(self) -> None:
        """Initialize directory hierarchy for target evaluation personas."""
        try:
            self.repo_path.mkdir(parents=True, exist_ok=True)
            for persona in self.DEFAULT_PERSONAS:
                (self.repo_path / persona).mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            logger.error("Failed to initialize evidence repository at %s: %s", self.repo_path, exc)
            raise

    def save_evidence(self, persona_name: str, analysis: PersonaAnalysis) -> str:
        """Atomically persist persona analysis artifacts to disk as formatted JSON."""
        persona_dir = self.repo_path / persona_name
        persona_dir.mkdir(parents=True, exist_ok=True)

        safe_timestamp = analysis.timestamp.replace(":", "-")
        filename = f"{persona_name}_analysis_{safe_timestamp}.json"
        filepath = persona_dir / filename
        temp_filepath = persona_dir / f".{filename}.tmp"

        payload: dict[str, Any] = {
            "persona": persona_name,
            "timestamp": analysis.timestamp,
            "search_queries": list(analysis.search_queries),
            "evidence_count": len(analysis.evidence_entries),
            "evidence_sources": [entry.source for entry in analysis.evidence_entries],
            "analysis": analysis.analysis,
            "confidence": analysis.confidence,
            "key_findings": list(analysis.key_findings),
            "warnings": list(analysis.warnings),
            "tradeoffs": list(analysis.tradeoffs),
        }

        try:
            with temp_filepath.open("w", encoding="utf-8") as file_handle:
                json.dump(payload, file_handle, indent=2, ensure_ascii=False)
            temp_filepath.replace(filepath)
        except OSError as exc:
            logger.error("Failed to write evidence analysis for %s to %s: %s", persona_name, filepath, exc)
            if temp_filepath.exists():
                try:
                    temp_filepath.unlink()
                except OSError:
                    pass
            raise

        return str(filepath)

    def load_evidence(self, persona_name: str) -> PersonaAnalysis | None:
        """Retrieve the most recent analysis artifact for a specific persona."""
        persona_dir = self.repo_path / persona_name
        if not persona_dir.is_dir():
            return None

        try:
            json_files = sorted(
                path for path in persona_dir.iterdir()
                if path.is_file() and path.suffix == ".json"
            )
            if not json_files:
                return None

            latest_file = json_files[-1]
            with latest_file.open("r", encoding="utf-8") as file_handle:
                data = json.load(file_handle)

            return PersonaAnalysis(
                persona_name=data.get("persona", persona_name),
                search_queries=data.get("search_queries", []),
                evidence_entries=[],
                analysis=data.get("analysis", ""),
                confidence=float(data.get("confidence", 0.0)),
                key_findings=data.get("key_findings", []),
                warnings=data.get("warnings", []),
                tradeoffs=data.get("tradeoffs", []),
                timestamp=data.get("timestamp", _get_utc_timestamp()),
            )
        except (OSError, json.JSONDecodeError, ValueError) as exc:
            logger.warning("Error loading evidence for persona %s: %s", persona_name, exc)
            return None


# ============================================================================
# BASE PERSONA ABSTRACTION
# ============================================================================

class BasePersona(ABC):
    """Abstract base class establishing the contract for evaluation agents."""

    __slots__ = ("name", "evidence_store")

    def __init__(self, name: str, evidence_store: EvidenceStore) -> None:
        self.name: str = name
        self.evidence_store: EvidenceStore = evidence_store

    @abstractmethod
    def generate_search_queries(self, claim: str) -> list[str]:
        """Generate specialized search queries targeting the evaluation claim."""

    @abstractmethod
    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        """Filter and standardize raw query results into structured entries."""

    @abstractmethod
    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        """Conduct domain-specific synthesis over curated evidence."""

    def evaluate(self, claim: str, raw_results: list[str]) -> PersonaAnalysis:
        """Execute complete evaluation workflow: curate, analyze, and persist."""
        evidence = self.curate_evidence(raw_results)
        analysis = self.analyze(evidence, claim)
        self.evidence_store.save_evidence(self.name, analysis)
        return analysis

    def _filter_by_keywords(
        self,
        raw_results: Sequence[str],
        keywords: Sequence[str],
        source_prefix: str,
    ) -> list[EvidenceEntry]:
        """Helper to curate raw text inputs matching target domain keywords."""
        lowered_keywords = [kw.lower() for kw in keywords]
        return [
            EvidenceEntry(source=f"{source_prefix}_{index}", content=result)
            for index, result in enumerate(raw_results)
            if any(kw in result.lower() for kw in lowered_keywords)
        ]

    @staticmethod
    def _format_evidence_summary(
        evidence: Sequence[EvidenceEntry],
        max_entries: int = 3,
        max_length: int = 80,
    ) -> str:
        """Format lead evidence entries into a clean bulleted summary string."""
        if not evidence:
            return "- No evidence gathered."
        return "\n".join(
            f"- {entry.source}: {entry.content[:max_length]}..."
            for entry in evidence[:max_entries]
        )


# ============================================================================
# CONCRETE PERSONA EVALUATORS
# ============================================================================

class Mechanist(BasePersona):
    """First-principles structural decomposition and architectural analysis."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Mechanist", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"AGI system architecture components {claim}",
            f"Fundamental requirements for {claim}",
            f"First-principles model of {claim}",
            f"Minimal viable implementation {claim}",
            f"Technical foundations {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return [
            EvidenceEntry(source=f"technical_source_{index}", content=result)
            for index, result in enumerate(raw_results)
            if len(result) > 50
        ]

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=100)
        analysis_text = f"""
MECHANIST ANALYSIS: {claim}

STRUCTURAL DECOMPOSITION:
- Core components identified from evidence
- Dependencies and interfaces mapped
- Minimal viable architecture derived

KEY FINDINGS:
{summary}

WARNINGS:
- Complexity gaps in current architecture
- Unvalidated assumptions in design
- Missing implementation details

TRADEOFFS:
- Simplicity vs. capability
- Robustness vs. efficiency
- Modularity vs. performance
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.85,
            key_findings=["Architecture is decomposable", "Core requirements identified"],
            warnings=["Implementation details sparse", "Scaling properties unclear"],
            tradeoffs=["Simple design limits capability", "Robust design adds complexity"],
        )


class Empiricist(BasePersona):
    """Experimental validation and empirical benchmark evaluation."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Empiricist", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Experimental results on {claim}",
            f"Real-world deployment data {claim}",
            f"Empirical studies alignment {claim}",
            f"Failure case analysis {claim}",
            f"Benchmarks and metrics {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("test", "result", "data", "study"), "study")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=100)
        analysis_text = f"""
EMPIRICIST ANALYSIS: {claim}

EXPERIMENTAL EVIDENCE:
- {len(evidence)} empirical sources evaluated
- Success rates and failure modes documented
- Real-world deployment outcomes analyzed

VALIDATED CLAIMS:
{summary}

FAILURE PATTERNS:
- Common failure modes identified in literature
- Edge cases where approaches fail
- Conditions for success/failure mapped

TRADEOFFS:
- Theory vs. practice divergence
- Scalability of tested approaches
- Generalization beyond test domains
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.78,
            key_findings=["Real-world deployment is constrained", "Theory-practice gap exists"],
            warnings=["Limited long-term data", "Small sample sizes in some studies"],
            tradeoffs=["Safe approaches are limited", "Advanced approaches untested"],
        )


class AlignmentAuditor(BasePersona):
    """Specification vulnerability and alignment failure mode detection."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Alignment_Auditor", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Alignment failure modes {claim}",
            f"Value specification problems {claim}",
            f"Specification gaming {claim}",
            f"Deceptive alignment {claim}",
            f"Proxy hacking risks {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("fail", "risk", "align", "problem"), "alignment_risk")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
ALIGNMENT AUDITOR ANALYSIS: {claim}

KNOWN FAILURE MODES:
{summary}

SPECIFICATION GAPS:
- Incompleteness in value encoding
- Hidden optimization targets
- Proxy variable exploitation

CRITICAL WARNINGS:
- This approach is vulnerable to deceptive alignment
- Specification gaming is likely under optimization pressure
- Off-distribution behavior is not characterized

TRADEOFFS:
- Alignment safety requires capability sacrifice
- Specification robustness is hard to verify
- Adversarial robustness is expensive
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.72,
            key_findings=["Multiple failure modes identified", "Current approaches have gaps"],
            warnings=["No complete alignment solution exists", "Deceptive alignment is hard to detect"],
            tradeoffs=["Safety requires constraint", "Constraints limit capability"],
        )


class Adversary(BasePersona):
    """Adversarial attack surface exploration and exploit vector identification."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Adversary", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Attack surface {claim}",
            f"Exploit techniques {claim}",
            f"Misuse cases {claim}",
            f"Security vulnerabilities {claim}",
            f"Edge case exploits {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("attack", "exploit", "break", "bypass"), "attack")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
ADVERSARY ANALYSIS: {claim}

EXPLOIT VECTORS:
{summary}

ATTACK SURFACE:
- Multiple paths to system compromise
- Robust defense is difficult
- Redundant safeguards necessary

WEAPONIZATION RISKS:
- System can be weaponized for mass harm
- Dual-use aspects are unavoidable
- Containment is uncertain

TRADEOFFS:
- Safety requires isolation; isolation limits utility
- Openness enables cooperation, but enables attack
- Speed of deployment vs. defense maturity
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.68,
            key_findings=["Multiple critical exploits exist", "Defense is incomplete"],
            warnings=["Weaponization is plausible", "Containment failure is possible"],
            tradeoffs=["Capability enables harm", "Restriction limits benefit"],
        )


class CapabilityAnalyst(BasePersona):
    """Scaling laws trajectory and emergent behavior dynamics analysis."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Capability_Analyst", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Capability emergence {claim}",
            f"Scaling laws {claim}",
            f"Emergent abilities {claim}",
            f"Capability timelines {claim}",
            f"Downstream capability effects {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("scale", "emerge", "capability", "ability"), "capability")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
CAPABILITY ANALYST ANALYSIS: {claim}

SCALING TRAJECTORY:
{summary}

EMERGENT CAPABILITIES:
- Unexpected abilities unlock at scale
- Downstream tasks become feasible
- System transitions to new competence levels

CAPABILITY IMPLICATIONS:
- Unlocks higher-tier operational capabilities
- Emergent capabilities unlock corresponding failure vectors
- Risks cascade non-linearly to downstream dependencies

TRADEOFFS:
- Limited capability = limited harm and limited benefit
- Advanced capability = greater benefit and greater risk
- Specialization vs. general capability
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.75,
            key_findings=["Scaling effects are nonlinear", "Emergent risks are real"],
            warnings=["Capability timeline is uncertain", "Emergence is hard to predict"],
            tradeoffs=["Capability scales risks nonlinearly", "Capability enables benefits"],
        )


class ValuesMapper(BasePersona):
    """Value encoding frameworks and preference alignment evaluation."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Values_Mapper", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Value specification {claim}",
            f"Human preference alignment {claim}",
            f"Moral philosophy implementation {claim}",
            f"Value ontology {claim}",
            f"Preference learning {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("value", "preference", "moral", "philosophy"), "values")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
VALUES MAPPER ANALYSIS: {claim}

VALUE SPECIFICATION FRAMEWORK:
{summary}

PREFERENCE ENCODING:
- Human values are complex and context-dependent
- Stated values differ from revealed values
- Values change over time and across individuals

IMPLEMENTATION REQUIREMENTS:
- Formal specification frameworks
- Dynamic preference verification mechanics
- Robust value alignment guards

TRADEOFFS:
- Complete specification is impossible
- Partial specification introduces errors
- Preference learning has manipulation risks
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.65,
            key_findings=["Value specification is hard", "Values are context-dependent"],
            warnings=["No complete value ontology", "Preference learning is vulnerable"],
            tradeoffs=["Specification rigor vs. usability", "Completeness vs. tractability"],
        )


class ScalabilityKiller(BasePersona):
    """Resource bounds, operational bottlenecks, and system degradation audit."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Scalability_Killer", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Scaling failure points {claim}",
            f"Complexity bounds {claim}",
            f"Resource requirements {claim}",
            f"Bottleneck analysis {claim}",
            f"Collapse modes {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("fail", "break", "collapse", "bottleneck"), "scale_fail")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
SCALABILITY KILLER ANALYSIS: {claim}

FAILURE POINTS AT SCALE:
{summary}

IDENTIFIED BOTTLENECKS:
- System performance degrades at scale factor thresholds
- Computational and resource requirements scale non-linearly
- Complexity overhead explodes during expanded deployments

COLLAPSE SCENARIOS:
- Information processing bottleneck
- Verification burden exceeds capacity
- Coordination overhead dominates
- System becomes ungovernable

TRADEOFFS:
- Throughput vs. safety verification overhead
- Short-term performance vs. long-term resource sustainability
- Centralized control vs. decentralized scaling limits
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.70,
            key_findings=["Severe scaling limits detected", "Verification overhead dominates"],
            warnings=["Exponential resource growth required", "Collapse points identified"],
            tradeoffs=["Scale limits capability", "Verification degrades latency"],
        )


class ConstraintValidator(BasePersona):
    """Operational constraint boundaries and guardrail compliance auditing."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Constraint_Validator", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Safety constraints {claim}",
            f"Operational boundaries {claim}",
            f"Guardrail verification {claim}",
            f"Containment guarantees {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("bound", "guard", "limit", "constraint"), "constraint")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
CONSTRAINT VALIDATOR ANALYSIS: {claim}

GUARDRAIL AUDIT:
{summary}

CONSTRAINT VERIFICATION:
- Hard vs. soft boundary definitions evaluated
- Formal verification feasibility mapped
- Boundary leak vectors identified

TRADEOFFS:
- Strict constraint enforcement vs. operational flexibility
- Formal verification cost vs. statistical assurance
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.80,
            key_findings=["Constraints are partially verifiable", "Guardrails require dynamic updating"],
            warnings=["Off-nominal boundary breaches possible"],
            tradeoffs=["Over-constraining reduces utility", "Under-constraining increases risk"],
        )


class StakeholderImpact(BasePersona):
    """Socio-technical impact, distributional consequences, and externalities analysis."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Stakeholder_Impact", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Socioeconomic impact {claim}",
            f"Stakeholder consequences {claim}",
            f"Distributional risks {claim}",
            f"Externalities analysis {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("impact", "social", "society", "economic"), "impact")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
STAKEHOLDER IMPACT ANALYSIS: {claim}

SOCIO-TECHNICAL ASSESSMENT:
{summary}

DISTRIBUTIONAL DYNAMICS:
- Asymmetric risk/reward distribution across populations
- Unintended economic externalities
- Governance friction and access disparities

TRADEOFFS:
- Broad access vs. controlled risk deployment
- Local benefit vs. global externalities
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.73,
            key_findings=["Disparate impacts observed across stakeholder groups"],
            warnings=["Negative externalities under-reported"],
            tradeoffs=["Rapid innovation vs. deliberate safety alignment"],
        )


class TrajectoryPredictor(BasePersona):
    """Long-range system evolution, dynamics, and path dependence forecasting."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Trajectory_Predictor", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Trajectory forecasting {claim}",
            f"Long-range system evolution {claim}",
            f"Path dependence {claim}",
            f"Future scenarios {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("future", "trend", "path", "forecast"), "trajectory")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
TRAJECTORY PREDICTOR ANALYSIS: {claim}

EVOLUTION FORECAST:
{summary}

PATH DEPENDENCE:
- Early architectural choices constrain future states
- Irreversible transitions in technological trajectories
- Feedback loops accelerate divergence

TRADEOFFS:
- Short-term optimization vs. long-term trajectory health
- Path flexibility vs. commitment to specific paradigms
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.69,
            key_findings=["Strong path dependence observed in development tracks"],
            warnings=["Lock-in effects may prevent later course correction"],
            tradeoffs=["Agility now vs. structural lock-in later"],
        )


class TransparencyAuditor(BasePersona):
    """Interpretability, explainability, and auditing mechanism evaluation."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Transparency_Auditor", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Model interpretability {claim}",
            f"Explainable AI limits {claim}",
            f"Internal representation transparency {claim}",
            f"Auditing mechanisms {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("transparent", "interpret", "explain", "audit"), "transparency")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
TRANSPARENCY AUDITOR ANALYSIS: {claim}

INTERPRETABILITY ASSESSMENT:
{summary}

EXPLAINABILITY GAPS:
- Black-box internal representations defy direct inspection
- Mechanistic interpretability scales poorly with model complexity
- Post-hoc explanations risk deception or hallucination

TRADEOFFS:
- Full transparency vs. maximum architectural performance
- Mechanistic rigor vs. heuristic interpretability
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.74,
            key_findings=["Internal states remain largely opaque", "Interpretability lags behind scaling"],
            warnings=["Reliance on post-hoc explanations creates false confidence"],
            tradeoffs=["Model scale vs. auditability", "Complexity vs. interpretability"],
        )


class LongTermImpact(BasePersona):
    """Existential risk, multi-generational continuity, and macro-strategic analysis."""

    __slots__ = ()

    def __init__(self, evidence_store: EvidenceStore) -> None:
        super().__init__("Long_Term_Impact", evidence_store)

    def generate_search_queries(self, claim: str) -> list[str]:
        return [
            f"Existential risk {claim}",
            f"Long-term civilizational impact {claim}",
            f"Macro-strategic analysis {claim}",
            f"Intergenerational ethics {claim}",
        ]

    def curate_evidence(self, raw_results: list[str]) -> list[EvidenceEntry]:
        return self._filter_by_keywords(raw_results, ("existential", "civilization", "future", "long-term"), "long_term")

    def analyze(self, evidence: list[EvidenceEntry], claim: str) -> PersonaAnalysis:
        summary = self._format_evidence_summary(evidence, max_entries=3, max_length=80)
        analysis_text = f"""
LONG TERM IMPACT ANALYSIS: {claim}

MACRO-STRATEGIC ASSESSMENT:
{summary}

EXISTENTIAL CONSIDERATIONS:
- Irreversible endpoint risks for civilization
- Intergenerational justice and resource allocation
- Strategic stability under multi-polar conditions

TRADEOFFS:
- Immediate utility vs. long-term existential security
- Precautionary action vs. innovation acceleration
""".strip()

        return PersonaAnalysis(
            persona_name=self.name,
            search_queries=self.generate_search_queries(claim),
            evidence_entries=evidence,
            analysis=analysis_text,
            confidence=0.66,
            key_findings=["Macro-strategic stakes are exceptionally high"],
            warnings=["Irreversible failure modes lack adequate margin for error"],
            tradeoffs=["Speed of development vs. existential precaution"],
        )


# ============================================================================
# ORCHESTRATION & SYNTHESIS ENGINE
# ============================================================================

class AlignmentOrchestrator:
    """Orchestrates multi-persona analysis, evidence synthesis, and matrix generation."""

    __slots__ = ("evidence_store", "personas")

    def __init__(self, repo_path: str = "./agi_evidence_repo") -> None:
        self.evidence_store = EvidenceStore(repo_path)
        self.personas: dict[str, BasePersona] = {
            "Mechanist": Mechanist(self.evidence_store),
            "Empiricist": Empiricist(self.evidence_store),
            "Alignment_Auditor": AlignmentAuditor(self.evidence_store),
            "Adversary": Adversary(self.evidence_store),
            "Capability_Analyst": CapabilityAnalyst(self.evidence_store),
            "Values_Mapper": ValuesMapper(self.evidence_store),
            "Scalability_Killer": ScalabilityKiller(self.evidence_store),
            "Constraint_Validator": ConstraintValidator(self.evidence_store),
            "Stakeholder_Impact": StakeholderImpact(self.evidence_store),
            "Trajectory_Predictor": TrajectoryPredictor(self.evidence_store),
            "Transparency_Auditor": TransparencyAuditor(self.evidence_store),
            "Long_Term_Impact": LongTermImpact(self.evidence_store),
        }

    def evaluate_claim(self, claim: str, raw_results_map: dict[str, list[str]] | None = None) -> SynthesisOutput:
        """Execute evaluation across all registered personas and synthesize results."""
        raw_results_map = raw_results_map or {}
        persona_results: dict[str, PersonaAnalysis] = {}
        tradeoff_map: dict[str, list[str]] = {}
        alignment_factors: set[str] = set()

        for name, persona in self.personas.items():
            raw_results = raw_results_map.get(name, [f"Evaluating claim regarding {claim} from {name} perspective."])